services:
  postgres:
    image: 'postgres:17-alpine3.19'
    environment:
      - 'POSTGRES_DB=speakers_db'
      - 'POSTGRES_PASSWORD=postgresql'
      - 'POSTGRES_USER=postgresql'
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m