ktor:
    application:
        modules:
            - com.geovannycode.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/speakers_db"
  user: postgresql
  password: postgresql